### ISSUE TITLE
Arrange entry "templates" is invalid

### ISSUE THREAD

**Issue by connerxyz** [lukasgeiter/mkdocs-awesome-pages-plugin#25] opened 2020-09-11 00:18 UTC
I have a portion of my site I'd like to use to document templates (things we create as part of our project not anything to do with MkDocs itself).

The site build breaks when I list 'templates' under arrange in the `docs/.pages` file.

```
arrange:
    - index.md
    - ...
    - templates
```

```
INFO    -  Cleaning site directory
--
243 | INFO    -  Building documentation to directory: /codebuild/...
244 | Traceback (most recent call last):
245 | File "/codebuild/.../mkdocs_awesome_pages_plugin/navigation.py", line 72, in _arrange_items
246 | return arrange(items, meta.arrange, lambda item: basename(self._get_item_path(item)))
247 | File "/codebuild/.../mkdocs_awesome_pages_plugin/arrange.py", line 29, in arrange
248 | raise InvalidArrangeEntry(entry)
249 | mkdocs_awesome_pages_plugin.arrange.InvalidArrangeEntry: Arrange entry "templates" is invalid.
```

Is this "invalid" because it's conflicting with potential MkDocs templates? Is there a workaround?

**Comment by lukasgeiter** [comment] 2020-09-11 06:51
The `arrange` option only works with entries that are known to MkDocs and appear in the navigation. Since `templates` doesn't have to do anything with MkDocs, maybe you can just omit it from the pages file?

**Comment by connerxyz** [comment] 2020-09-14 15:02
The site *needs* to have a templates section, so I can't just omit it from pages file. 

That templates section is listed, just like the other sections, but the won't build when there's a section called "templates".

I'm trying to figure out how I can have a templates section in the site.

**Comment by lukasgeiter** [comment] 2020-09-14 15:18
The `arrange` option does not allow you to _add_ entries to the MkDocs navigation, it can merely change their order.

I'm planning to implement a more powerful version of the feature in the future and I'll take this requirement in consideration.

**Comment by connerxyz** [comment] 2020-09-14 15:19
But it works if I use "templates+" and not when I use "templates"... I'm not sure we are talking about the same thing. I'm digging through the plugin source right now.

**Comment by lukasgeiter** [comment] 2020-09-14 15:26
Hmm that's interesting. Could you provide me with a minimal example to reproduce the problem?

**Comment by connerxyz** [comment] 2020-09-14 16:19
Yes. See here https://github.com/connerxyz/templates-issue-example

**Comment by connerxyz** [comment] 2020-09-14 16:23
And then here's the working version. https://github.com/connerxyz/templates-issue-example/tree/working-version

**Comment by connerxyz** [comment] 2020-09-14 16:23
It's like MkDocs removes `docs/templates` directory before building.

**Comment by connerxyz** [comment] 2020-09-14 16:56
Possibly related https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin/issues/25

**Comment by lukasgeiter** [comment] 2020-09-14 17:20
Thanks for the example. We were indeed not talking about the same thing. I thought that your `templates` directory didn't contain any markdown files...

As you have seem to figured out by now as well, MkDocs is not including `docs/templates` when building. Why that is I don't know. I just know that it is unrelated to this plugin, therefore I'll close the issue. Let's see what comes out of issue mkdocs/mkdocs#2185...

**Closed by lukasgeiter** 2020-09-14 17:20 UTC
